"""add last_reset to users

Revision ID: 491b90fe430d
Revises: 11d12185344c
Create Date: 2025-06-26 11:54:35.024365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491b90fe430d'
down_revision: Union[str, None] = '11d12185344c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('last_reset')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('creci', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('creci')
        batch_op.drop_column('nome')
        batch_op.drop_column('last_reset')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
