"""Remove unique constraint from subscription_plans name

Revision ID: 984b2c3ed9c9
Revises: 5bd49824d803
Create Date: 2025-06-10 14:44:02.267346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984b2c3ed9c9'
down_revision: Union[str, None] = '5bd49824d803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_name'))
        batch_op.create_index(batch_op.f('ix_subscription_plans_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_name'))
        batch_op.create_index(batch_op.f('ix_subscription_plans_name'), ['name'], unique=1)

    # ### end Alembic commands ###
